name: Update README

on:
  push:
    paths:
    - 'README.md'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout revyos/revyos repository
      uses: actions/checkout@v2
      with:
        repository: revyos/revyos
        path: revyos

    - name: Replace relative links in README.md
      run: |
        sed -i -E 's|(\[.*\])\(([^:]*)\)|\1(https://github.com/revyos/docs/blob/master/docs/\2)|g' revyos/README.md

    - name: Copy to destination repository
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.ACCESS_TOKEN }}
        src_path: ../revyos/README.md
        dst_path: profile/
        dst_owner: KamijoToma
        dst_repo_name: revyos-github